"""Dump data/eu_competitors.db to readable JSON under reports/data/ so the
collected census + profiles + leader insights live in the repo without the
binary .db (which is gitignored and regenerated by scripts/collect.py).

    python reports/export_json.py
"""
import json
import sqlite3
from pathlib import Path

DB = Path(__file__).resolve().parents[1] / "data" / "eu_competitors.db"
OUT = Path(__file__).resolve().parent / "data"
OUT.mkdir(exist_ok=True)

_JSON_FIELDS = {
    "competitor_profiles": ("target_applications", "key_partnerships", "differentiators", "source_urls"),
    "leader_insights": ("success_factors", "application_suggestions", "market_route_suggestions", "source_urls"),
}

db = sqlite3.connect(DB)
db.row_factory = sqlite3.Row

for table in ("discovered_companies", "competitor_profiles", "leader_insights", "discovered_articles"):
    rows = []
    for r in db.execute(f"select * from {table}"):
        d = dict(r)
        for f in _JSON_FIELDS.get(table, ()):
            if f in d:
                try:
                    d[f] = json.loads(d[f] or "[]")
                except (json.JSONDecodeError, TypeError):
                    d[f] = []
        rows.append(d)
    path = OUT / f"{table}.json"
    path.write_text(json.dumps(rows, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    print(f"{path.relative_to(Path(__file__).resolve().parents[1])}: {len(rows)} rows")
